In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {'one': pd.Series([1,2,5], index = ['a','b','e']),
       'two':pd.Series([1,2,3,4], index = ['a','b','c','d']),}
table = pd.DataFrame(data)
print('Befrore:\n',table)

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(table)
imputed_data = imputer.transform(table.values)
print('After:\n',pd.DataFrame(imputed_data, columns = ['one','two']))

Befrore:
    one  two
a  1.0  1.0
b  2.0  2.0
c  NaN  3.0
d  NaN  4.0
e  5.0  NaN
After:
         one  two
0  1.000000  1.0
1  2.000000  2.0
2  2.666667  3.0
3  2.666667  4.0
4  5.000000  2.5


C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


In [11]:
data = {'customer-id':pd.Series([1,2,3,4,5]),'Loan_type':pd.Series(['Home Loan','Personal Loan',
                                                                   'Educational Loan','Home Loan','Credit Loan']),
       'Income': pd.Series(['30k','15k','25k','40k','35k'])}
loan_info = pd.DataFrame(data)

print(loan_info)

   customer-id         Loan_type Income
0            1         Home Loan    30k
1            2     Personal Loan    15k
2            3  Educational Loan    25k
3            4         Home Loan    40k
4            5       Credit Loan    35k


In [9]:
loan_info = pd.get_dummies(loan_info, prefix_sep = '_',drop_first = True)
print(loan_info)

   customer-id  Loan_type_Educational Loan  Loan_type_Home Loan  \
0            1                           0                    1   
1            2                           0                    0   
2            3                           1                    0   
3            4                           0                    1   
4            5                           0                    0   

   Loan_type_Personal Loan  Income_25k  Income_30k  Income_35k  Income_40k  
0                        0           0           1           0           0  
1                        1           0           0           0           0  
2                        0           1           0           0           0  
3                        0           0           0           0           1  
4                        0           0           0           1           0  


In [12]:
data = {'customer-id':pd.Series([1,2,3,4,5]),'Loan_type':pd.Series(['Home Loan','Personal Loan',
                                                                   'Educational Loan','Home Loan','Credit Loan']),
       'Income': pd.Series(['30k','15k','25k','40k','35k'])}
loan_info = pd.DataFrame(data)
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
loan_info_upd = loan_info.apply(labelencoder.fit_transform)


print(loan_info_upd)

   customer-id  Loan_type  Income
0            0          2       2
1            1          3       0
2            2          1       1
3            3          2       4
4            4          0       3


In [17]:
data = {'customer-id':pd.Series([1,2,3,4,5]),'Loan_type':pd.Series(['Home Loan','Personal Loan',
                                                                   'Educational Loan','Home Loan','Credit Loan']),
       'Income': pd.Series(['30k','15k','25k','40k','35k'])}
loan_info = pd.DataFrame(data)
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
x = onehotencoder.fit_transform(loan_info).toarray()
print(x)

[[1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0.]]
