In [1]:
import numpy as np
a = np.array([[[[4,5,6,4]],[[5,6,5,4]],[[4,5,6,8]]],
             [[[0,0,0,0]],[[4,5,6,7]],[[1,1,1,1]]]])

In [2]:
a.shape

(2, 3, 1, 4)

In [5]:
a

array([[[[4, 5, 6, 4]],

        [[5, 6, 5, 4]],

        [[4, 5, 6, 8]]],


       [[[0, 0, 0, 0]],

        [[4, 5, 6, 7]],

        [[1, 1, 1, 1]]]])

In [5]:
##3,2,1,4,8
a = np.array([[[[[1,2,3,4,5,6,7,8],[2,3,4,5,6,7,8,9],
                [3,4,5,6,7,8,9,0],[4,5,6,7,8,9,0,1]]],
              [[[1,2,3,4,5,6,7,8],[2,3,4,5,6,7,8,9],[3,4,5,6,7,8,9,0],[0,1,2,3,4,5,6,7]]]],
             [[[[1,2,3,4,5,6,7,8],[2,3,4,5,6,7,8,9],
                [3,4,5,6,7,8,9,0],[4,5,6,7,8,9,0,1]]],
              [[[1,2,3,4,5,6,7,8],[2,3,4,5,6,7,8,9],[3,4,5,6,7,8,9,0],[0,1,2,3,4,5,6,7]]]],[[[[1,2,3,4,5,6,7,8],[2,3,4,5,6,7,8,9],
                [3,4,5,6,7,8,9,0],[4,5,6,7,8,9,0,1]]],
              [[[1,2,3,4,5,6,7,8],[2,3,4,5,6,7,8,9],[3,4,5,6,7,8,9,0],[0,1,2,3,4,5,6,7]]]]])

In [6]:
a.shape

(3, 2, 1, 4, 8)

In [7]:
a

array([[[[[1, 2, 3, 4, 5, 6, 7, 8],
          [2, 3, 4, 5, 6, 7, 8, 9],
          [3, 4, 5, 6, 7, 8, 9, 0],
          [4, 5, 6, 7, 8, 9, 0, 1]]],


        [[[1, 2, 3, 4, 5, 6, 7, 8],
          [2, 3, 4, 5, 6, 7, 8, 9],
          [3, 4, 5, 6, 7, 8, 9, 0],
          [0, 1, 2, 3, 4, 5, 6, 7]]]],



       [[[[1, 2, 3, 4, 5, 6, 7, 8],
          [2, 3, 4, 5, 6, 7, 8, 9],
          [3, 4, 5, 6, 7, 8, 9, 0],
          [4, 5, 6, 7, 8, 9, 0, 1]]],


        [[[1, 2, 3, 4, 5, 6, 7, 8],
          [2, 3, 4, 5, 6, 7, 8, 9],
          [3, 4, 5, 6, 7, 8, 9, 0],
          [0, 1, 2, 3, 4, 5, 6, 7]]]],



       [[[[1, 2, 3, 4, 5, 6, 7, 8],
          [2, 3, 4, 5, 6, 7, 8, 9],
          [3, 4, 5, 6, 7, 8, 9, 0],
          [4, 5, 6, 7, 8, 9, 0, 1]]],


        [[[1, 2, 3, 4, 5, 6, 7, 8],
          [2, 3, 4, 5, 6, 7, 8, 9],
          [3, 4, 5, 6, 7, 8, 9, 0],
          [0, 1, 2, 3, 4, 5, 6, 7]]]]])

In [8]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
b.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
c = np.arange(30)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
x = c.reshape((3,2,5))

In [15]:
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [16]:
x.reshape((3,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [17]:
x.reshape((10,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [19]:
y=x.reshape((6,5))
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [20]:
y.transpose()

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [24]:
v = np.array([[1,2,3,4,5]])
np.concatenate((y,v),axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [ 1,  2,  3,  4,  5]])

In [26]:
q = np.array([[1,2,3,4,5,6]])
np.concatenate((y,q.T),axis = 1)

array([[ 0,  1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  9,  2],
       [10, 11, 12, 13, 14,  3],
       [15, 16, 17, 18, 19,  4],
       [20, 21, 22, 23, 24,  5],
       [25, 26, 27, 28, 29,  6]])

In [40]:
d = np.concatenate((y,q.T),axis = 1)
d

array([[ 0,  1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  9,  2],
       [10, 11, 12, 13, 14,  3],
       [15, 16, 17, 18, 19,  4],
       [20, 21, 22, 23, 24,  5],
       [25, 26, 27, 28, 29,  6]])

In [41]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [42]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [43]:
y.reshape(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [45]:
np.squeeze(y)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [46]:
np.unique(y)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [48]:
d

array([[ 0,  1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  9,  2],
       [10, 11, 12, 13, 14,  3],
       [15, 16, 17, 18, 19,  4],
       [20, 21, 22, 23, 24,  5],
       [25, 26, 27, 28, 29,  6]])

In [49]:
np.unique(d)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [50]:
np.unique(d,axis = 1)

array([[ 0,  1,  1,  2,  3,  4],
       [ 5,  2,  6,  7,  8,  9],
       [10,  3, 11, 12, 13, 14],
       [15,  4, 16, 17, 18, 19],
       [20,  5, 21, 22, 23, 24],
       [25,  6, 26, 27, 28, 29]])

In [51]:
np.unique(d,axis = 0)

array([[ 0,  1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  9,  2],
       [10, 11, 12, 13, 14,  3],
       [15, 16, 17, 18, 19,  4],
       [20, 21, 22, 23, 24,  5],
       [25, 26, 27, 28, 29,  6]])

In [60]:
d1 = np.array([[0,1,2,3,4,1]])
d2 = np.concatenate((d,d1),axis =0)

In [61]:
d2

array([[ 0,  1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  9,  2],
       [10, 11, 12, 13, 14,  3],
       [15, 16, 17, 18, 19,  4],
       [20, 21, 22, 23, 24,  5],
       [25, 26, 27, 28, 29,  6],
       [ 0,  1,  2,  3,  4,  1]])

In [62]:
np.unique(d2,axis = 0)

array([[ 0,  1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  9,  2],
       [10, 11, 12, 13, 14,  3],
       [15, 16, 17, 18, 19,  4],
       [20, 21, 22, 23, 24,  5],
       [25, 26, 27, 28, 29,  6]])