In [2]:
import numpy as np
a = np.array([30,60,90])
a

array([30, 60, 90])

In [3]:
np.sin(a)

array([-0.98803162, -0.30481062,  0.89399666])

In [5]:
b = np.cos(a)
b

array([ 0.15425145, -0.95241298, -0.44807362])

In [6]:
np.floor(b)

array([ 0., -1., -1.])

In [8]:
np.ceil(b)

array([ 1., -0., -0.])

In [9]:
np.round(b,3)


array([ 0.154, -0.952, -0.448])

In [10]:
np.rint(b)

array([ 0., -1., -0.])

In [18]:
arr = np.linspace(1,5,6)

In [19]:
arr = arr.reshape((3,2))

In [20]:
arr

array([[1. , 1.8],
       [2.6, 3.4],
       [4.2, 5. ]])

In [21]:
np.floor(arr)

array([[1., 1.],
       [2., 3.],
       [4., 5.]])

In [22]:
np.ceil(arr)

array([[1., 2.],
       [3., 4.],
       [5., 5.]])

In [23]:
np.round(arr,2)

array([[1. , 1.8],
       [2.6, 3.4],
       [4.2, 5. ]])

In [24]:
np.sin(np.deg2rad(a))

array([0.5      , 0.8660254, 1.       ])

In [25]:
np.rad2deg(90)

5156.620156177409

In [26]:
np.sum(a)

180

In [29]:
np.sum(arr,axis=0)

array([ 7.8, 10.2])

In [30]:
np.sum(arr,axis=1)

array([2.8, 6. , 9.2])

In [31]:
np.sum(arr)

18.0

In [33]:
arr2 = np.linspace(2,6,6).reshape((3,2))
arr2

array([[2. , 2.8],
       [3.6, 4.4],
       [5.2, 6. ]])

In [34]:
arr+arr2

array([[ 3. ,  4.6],
       [ 6.2,  7.8],
       [ 9.4, 11. ]])

In [35]:
arr*arr2

array([[ 2.  ,  5.04],
       [ 9.36, 14.96],
       [21.84, 30.  ]])

In [38]:
a = np.linspace(1,9,9).reshape((3,3))
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [39]:
b = np.linspace(4,9,6).reshape((3,2))
b

array([[4., 5.],
       [6., 7.],
       [8., 9.]])

In [41]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])