# Problem Statement 1: Write a Python program to multiply a 𝑀 × 𝑁 matrix by 𝑁 × 𝐴 matrix and create a real matrix product.

In [5]:
import numpy as np

In [6]:
mat1 = np.linspace(5,60,12).reshape(4,3)
print("First matrix:\n", mat1)
mat2 = np.linspace(10,40,6).reshape(3,2)
print("Second matrix:\n",mat2)

First matrix:
 [[ 5. 10. 15.]
 [20. 25. 30.]
 [35. 40. 45.]
 [50. 55. 60.]]
Second matrix:
 [[10. 16.]
 [22. 28.]
 [34. 40.]]


In [7]:
mat3 = np.dot(mat1,mat2)
print("Dot Product of two Matrix:\n",mat3)

Dot Product of two Matrix:
 [[ 780.  960.]
 [1770. 2220.]
 [2760. 3480.]
 [3750. 4740.]]


# Problem Statement 2: Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only.


In [8]:
import numpy as np
arr = np.array(["DHARMENDRA","PYTHON","edureka","369","data science","562","JAVA"])
print("Orginal array:\n",arr)

Orginal array:
 ['DHARMENDRA' 'PYTHON' 'edureka' '369' 'data science' '562' 'JAVA']


In [9]:
digit_only = np.char.isdigit(arr)
lower_only = np.char.islower(arr)
upper_only = np.char.isupper(arr)
print("Digits Only =",digit_only)
print("Lower case only =",lower_only)
print("Upper ocase only =",upper_only)


Digits Only = [False False False  True False  True False]
Lower case only = [False False  True False  True False False]
Upper ocase only = [ True  True False False False False  True]


# Problem Statement 3: Write a program that reads two space-separated positive integers 𝑋 and 𝑌 as input and perform the following tasks:

In [10]:
import numpy as np

In [25]:
lst = list(map(int,input().split()))
print(lst)
x = lst[0]
y = lst[1]

7 9
[7, 9]


# 1. Create a list (lst1) starting at one (1) with 16 elements at a step of x

In [26]:
def mul(a):
    return(a*x)
lst1 = map(mul,(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16))
lst1 = list(lst1)
print(lst1)


[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112]


# 2. Create a list (lst2) starting at one (1) with 16 elements at a step of y

In [27]:
def mul(a):
    return(a*y)
lst2 = map(mul,(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16))
lst2 = list(lst2)
print(lst2)

[9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99, 108, 117, 126, 135, 144]


# 3. Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively

In [28]:
import numpy as np
np1 = np.array(lst1)
np2 = np.array(lst2)
print("np1=",np1)
print("np2=",np2)

np1= [  7  14  21  28  35  42  49  56  63  70  77  84  91  98 105 112]
np2= [  9  18  27  36  45  54  63  72  81  90  99 108 117 126 135 144]


# 4. Reshape both the NumPy arrays to (4,4)

In [29]:
np1 = np1.reshape(4,4)
np2 = np2.reshape(4,4)
print("np1=",np1)
print("np2=",np2)

np1= [[  7  14  21  28]
 [ 35  42  49  56]
 [ 63  70  77  84]
 [ 91  98 105 112]]
np2= [[  9  18  27  36]
 [ 45  54  63  72]
 [ 81  90  99 108]
 [117 126 135 144]]


# 5. Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -np2)

In [30]:
np3 = np1-np2

In [31]:
print(np3)

[[ -2  -4  -6  -8]
 [-10 -12 -14 -16]
 [-18 -20 -22 -24]
 [-26 -28 -30 -32]]


# 6. Print all the elements of np3 in a single dimension list

In [32]:
np3 = np3.ravel()

In [33]:
print(np3)

[ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30 -32]


In [34]:
lst_final = list(np3)
print(lst_final)

[-2, -4, -6, -8, -10, -12, -14, -16, -18, -20, -22, -24, -26, -28, -30, -32]


# Problem Statement 4: Write a Python program that takes two integer-NumPy arrays, 𝑃 and 𝑄 of shape [3 ∗ 3] 

In [35]:
P = np.array([54,78,56,95,84,45,87,12,25])
Q = np.array([12,42,36,21,45,24,26,26,32])
print("P=",P)
print("Q=",Q)

P= [54 78 56 95 84 45 87 12 25]
Q= [12 42 36 21 45 24 26 26 32]


In [36]:
R = P-Q
R = R.reshape(3,3)
print(R)

[[ 42  36  20]
 [ 74  39  21]
 [ 61 -14  -7]]
