In [ ]:
## Numpy: math calculation

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [4]:
len(dir(np))

608

In [5]:
# Numpy array from list
arr = np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [7]:
# Numpy array from tupple
arr = np.array((1,2,3,4,5))
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# Numpy array from set
arr = np.array({1,2,3,4,5})
print(arr)
type(arr)

{1, 2, 3, 4, 5}


numpy.ndarray

In [12]:
# Numpy array : attributes
arr = np.array([1,2,3,4,5])
print(arr.ndim)    #d dimmension of array
print(arr.shape) # number of row and column
print(arr.size) # total number of element
print(arr.dtype)  # the data type of contents of array
print(arr.itemsize) # number of bytes used to store the array elemnets

1
(5,)
5
int32
4


In [17]:
# Numpy array : attributes
arr = np.array([[1,2,3,4,5],[14,52,1,4,8],[4,5,6,8,7]])
print(arr)
print(arr.ndim)    #d dimmension of array
print(arr.shape) # number of row and column
print(arr.size) # total number of element
print(arr.dtype)  # the data type of contents of array
print(arr.itemsize) # number of bytes used to store the array elemnets

[[ 1  2  3  4  5]
 [14 52  1  4  8]
 [ 4  5  6  8  7]]
2
(3, 5)
15
int32
4


In [18]:
## Ones() and zeros()
arr = np.ones((5,5))
print(arr)
arr = np.zeros((5,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
# copy
import numpy as np
a = np.array([1,2,3])
print(id(a))    
b =a
print(id(b))    
c=a.copy()
print(id(c))    
a[0]=858585
print(a)
print(b)
print(c)

1759672674800
1759672674800
1759672556688
[858585      2      3]
[858585      2      3]
[1 2 3]


In [27]:
# arange
import numpy as np
arr = np.arange(0,20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [28]:
# arange
import numpy as np
arr = np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [31]:
# arange
import numpy as np
arr = np.arange(0,20,1/2)
print(arr)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]


In [32]:
# linspace
arr = np.linspace(0,20,5)
print(arr)

[ 0.  5. 10. 15. 20.]


In [33]:
## Airthmatic operator
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

print(a+b)
print(b-a)
print(a*b)
print(a/b)

[ 5  7  9 11 13]
[3 3 3 3 3]
[ 4 10 18 28 40]
[0.25       0.4        0.5        0.57142857 0.625     ]


In [34]:
## Matrix product
import numpy as np
a = np.arange(0,9).reshape(3,3)
b = np.ones((3,3))
print(a)
print(b)

print(np.dot(a,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [44]:
## iniversal function

import numpy as np

arr = np.array([4,9,16,25])
print(arr)
print(np.sqrt(arr))
print(np.log(arr))

      


[ 4  9 16 25]
[2. 3. 4. 5.]
[1.38629436 2.19722458 2.77258872 3.21887582]


In [47]:
## Aggregate functions

print(arr.sum())
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.std())


54
4
25
13.5
7.88986691902975


In [52]:
## Logical fuctions
import numpy as np
arr = np.array([[True,False],[True,False]])
print(arr)
print(np.all([arr]))

#overall

print(np.any([arr], axis = 1))

[[ True False]
 [ True False]]
False
[[ True False]]


In [53]:
## Logical fuctions
import numpy as np
arr = np.array([[True,False],[True,False]])
print(arr)


#overall
print(np.any([arr]))
print(np.any([arr], axis = 1))

[[ True False]
 [ True False]]
True
[[ True False]]
