In [ ]:
## Indexing in Numpy array`b

In [7]:
import numpy as np
arr = np.arange(21,26)

arr
print(arr)

[21 22 23 24 25]


In [8]:
#get 22
print(arr[1])
print(arr[2])
print(arr[-4])
print(arr[-3])
print(arr[-2])

22
23
22
23
24


In [9]:
print(arr[1:4])
print(arr[-4:-1])

[22 23 24]
[22 23 24]


In [11]:
## Indexing 2D
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(a[1:3, 1:3])

[[5 6]
 [8 9]]


In [17]:
print(a[1:2,1:2])
print(a[-2:-1,-2:-1])

[[5]]
[[5]]


In [20]:
print(a[0:3,1:2])
print(a[-3:,-2:-1])

[[2]
 [5]
 [8]]
[[2]
 [5]
 [8]]


In [25]:
# Changing the shape of array
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [29]:
print(a.reshape(3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [32]:
print(a.resize(3,3))
print(a)

None
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
## ravel

a = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a)
print(a.ndim)
print(a.ravel())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[1 2 3 4 5 6 7 8 9]


In [34]:
## Transpose
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
print(np.transpose(a))
print(a)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
## Joining the array

a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]]


In [44]:
## Axis = None
print(np.concatenate((a,b)))
np.concatenate((a,b), axis = None)

[[1 2]
 [3 4]
 [5 6]]


array([1, 2, 3, 4, 5, 6])

In [47]:
# Axis = 1
(np.concatenate((a,b.T), axis = 1))

array([[1, 2, 5],
       [3, 4, 6]])

In [49]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
## stacking
import numpy as np
a = np.array([1,2,3])
b = np.array([10,20,30])
np.stack((a,b))

array([[ 1,  2,  3],
       [10, 20, 30]])

In [58]:
# column stacking
import numpy as np
a = np.array([1,2,3])
b = np.array([10,20,30])
c = np.array([100,200,300]) 
np.column_stack((a,b,c))

array([[  1,  10, 100],
       [  2,  20, 200],
       [  3,  30, 300]])

In [60]:
## split arrays: split(), hsplit(), vsplit()
x = np.arange(9)
print(x)
np.split(x,3)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [61]:
x = np.arange(9)
print(x)
np.hsplit(x,3)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [65]:
x = np.arange(16).reshape(4,4)
print(x)
np.vsplit(x,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [66]:
x = np.arange(16).reshape(4,4)
print(x)
np.hsplit(x,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [67]:
x = np.arange(16).reshape(4,4)
print(x)
np.vsplit(x,4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [68]:
x = np.arange(16).reshape(4,4)
print(x)
np.hsplit(x,4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.ndim)
print(arr)
print(arr.ravel)
print(arr.ndim)

2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<built-in method ravel of numpy.ndarray object at 0x0000020C0D55ACF0>
2
